#!/usr/bin/env bash
# Configures /etc/hosts so localhost resolves to 127.0.0.2 and facebook.com to 8.8.8.8
sed -i -E 's/^127\.0\.0\.1[[:space:]]+localhost/127.0.0.2\tlocalhost/' /etc/hosts
echo -e '8.8.8.8\tfacebook.com' >> /etc/hosts
